# https://yarnpkg.com/configuration/yarnrc

approvedGitRepositories:
  - '**'

changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - '!{docs,src/**,{CHANGELOG,LICENSE,README}.md,package.json}'
  - '**/*.snap'
  - '**/*.spec.mts'
  - '**/*.spec-d.mts'

compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

enableInlineBuilds: true

enableScripts: true

enableTransparentWorkspaces: false

injectEnvironmentFiles:
  - .env.repo?
  - .env.vars?

nmHoistingLimits: dependencies

nodeLinker: node-modules

npmMinimalAgeGate: 0

patchFolder: ./patches

yarnPath: .yarn/releases/yarn-4.16.0.cjs
